name: WATU TEst
favicon: null
layout_spectrum: 0.9872092187870294
typography_spectrum: 0.07219
title: WATU Test
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.8084993092343211
  lightness: 0.5011641145683825
  saturation: 0.9160412694327533
  rhythmicContrast: 0.7720719284843653
purpose: []
